/*******************************************************************
  Brain-wave recognizer
  - Assumed sampling-rate: 128 Sa/s
*******************************************************************/


#include <ap_int.h>
#include <cstdio>


#define N 32        //Number taps (filter size)
#define SHIFT 14    // Fixed-point scale for Q2.14 format (1 sign, 1 int, 14 fraction) => multiplying floats by 2^14
                    // Shifting1<<14 instead of 16384 directly for reading clarity without time penalty

/* ---------- Five band-pass for 5 brain waves (generated by python script, Q2.14)  ---------
0 = Delta, 1 = Theta, 2 = Alpha, 3 = Beta, 4 = Gamma
------------------------------------------------------- */

static const ap_int<16> filters[5][N] = {
  /* 0 : Delta 0.5-4 Hz */ {
        -12,-3,11,37,82,152,249,374,524,691,866,1039,1196,1327,1420,1469,1469,1420,1327,1196,1039,866,691,524,374,249,152,82,37,11,-3,-12},
  /* 1 : Theta 4-8 Hz */  {
       -16,-55,-120,-223,-361,-514,-642,-699,-638,-429,-72,402,933,1440,1837,2055,2055,1837,1440,933,402,-72,-429,-638,-699,-642,-514,-361,-223,-120,-55,-16},
  /* 2 : Alpha 8-12 Hz */  {
    26,87,168,256,298,219,-33,-446,-915,-1268,-1326,-983,-265,652,1500,2008,2008,1500,652,-265,-983,-1326,-1268,-915,-446,-33,219,298,256,168,87,26},
  /* 3 : Beta 12-30 Hz */ {
       -28,-6,-6,-88,-142,50,337,261,-16,255,748,-127,-2353,-2951,102,3946,3946,102,-2951,-2353,-127,748,255,-16,261,337,50,-142,-88,-6,-6,-28},
  /* 4 : Gamma 30-100 Hz */ {
    19,-14,-50,52,52,40,-332,208,101,501,-1290,541,-50,2924,-6114,3413,3413,-6114,2924,-50,541,-1290,501,101,208,-332,40,52,52,-50,-14,19}
};


/* ---------- Three levels of sens_sel (Q2.14)  ---------
0 = Low, 1 = Medium, 2 = High
------------------------------------------------------- */
static const ap_int<16> thresholders[3] = {
    /* 0.10FS? * 2.14Format + 0.5? */
    (ap_int<16>) (0.10 * (1<<SHIFT) + 0.5),   // low  ≈ 0.10·FS
    (ap_int<16>) (0.18 * (1<<SHIFT) + 0.5),   // mid  ≈ 0.18·FS
    (ap_int<16>) (0.25 * (1<<SHIFT) + 0.5)    // high ≈ 0.25·FS
};



void brainwave_recognizer(
    ap_int<16> sample,
    ap_uint<3> band_sel, // 0-4 for Delta, Theta, Alpha, Beta, Gamma
    ap_uint<2> sens_sel, // 0-2 for Low, Medium, High
    bool &flag_out // Output signal to indicate if the brain wave is detected
){

    #pragma HLS INTERFACE ap_none  port=sample
    #pragma HLS INTERFACE ap_none  port=band_sel
    #pragma HLS INTERFACE ap_none  port=sens_sel
    #pragma HLS INTERFACE ap_none  port=flag_out
    #pragma HLS INTERFACE ap_ctrl_none port=return
    #pragma HLS PIPELINE II=1

    static ap_int<16> x_reg[N]; 
    
    //Accumulator (16*16 => 32 (4.28) bits + accumulator ≈ 36 (8.28) !!with 32 taps)
    ap_int<36> acc = 0;

    // We "push" the value inside => convolution easier
    for (int i = N - 1; i > 0; i--) {
        #pragma HLS UNROLL
        x_reg[i] = x_reg[i - 1];
    }
    x_reg[0] = sample;

    /*
    Unrolled loop to shift the register, 
    which means combinationally in one cycle (Not pipeline)
        x_reg[31] = x_reg[30];
        x_reg[30] = x_reg[29];
        ...
        x_reg[1] = x_reg[0];
    */

    /* ------------- Convolution ------------- */
    ap_uint<3> safe_band = (band_sel > 4) ? ap_uint<3>(4) : band_sel;
    const ap_int<16> *chosen_filter = filters[safe_band]; // Get the filter coefficients for the selected band
    for (int i = 0; i < N; i++) {
        #pragma HLS UNROLL
        acc += x_reg[i] * chosen_filter[i];
    }

    ap_int<16> trunc = acc >> SHIFT;
    
    #ifdef HLS_DEBUG_PRINT
    printf("trunc = %.4f\n", ((float)trunc.to_int()) / (1 << SHIFT));
    // 2.14 from Q8.28 to Q8.14 then truncated to 2.14 because of ap_int<16> type
    #endif
    /*
        - A 32-element shift register (x_reg[])
        - 32 parallel multipliers
        - A pipelined adder tree (16 - 8 - 4 - 2 - 1)
        - A final right-shift (>> SHIFT) and truncation to ap_int<16>
    */




    /* ----------  Rectify (magnitude)  ---------- */
    ap_uint<16> mag = (trunc < 0) ? (ap_uint<16>)(-trunc) : (ap_uint<16>)trunc;



    /*
        ----------  1-pole IIR envelope  ---------- 
        It follows power concept but can work also with less than a full period (in this case with an implied 128 sampling rate, with 8 taps we get 8/16, which is half period)
        I say 16 because 8Hz/128Hz
    */
    static ap_uint<18> env = 0;         // extra bits to avoid overflow
    // α = 1/8  ➜  simple right shift implements (1-α)
    env = env - (env >> 3) + mag;       // y[n] = (7/8)·y[n-1] + (1/8)·mag



    /* ------------- Thresholding ------------- */
    const ap_uint<18> THRESHOLD = (ap_uint<18>)(thresholders[sens_sel]) << 3;
    // Low:  1638 × 8 = 13,104
    // Mid:  2949 × 8 = 23,592
    // High: 4096 × 8 = 32,768

    static ap_uint<8> counter = 0;

    if (env > THRESHOLD) {
        if (counter < 255) counter++;
        #ifdef HLS_DEBUG_PRINT
        printf("%i\n", counter.to_uint());
        #endif
    } else if (counter > 0) {
        counter--;
    }

    #ifdef HLS_DEBUG_PRINT
    printf("sample=%d  flag=%d\n", sample.to_int(), flag_out);
    #endif

    flag_out = (counter >= 40);
}
